import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import Navbar from '../Components/Navbar'
import SocialLinks from "@/Components/Social-Links";
import About from "@/Components/About-component";
import html from '../public/html5.png'
import css from '../public/css.png'
import sass from '../public/sass.png'
import js from '../public/js.png'
import react from '../public/react.png'
import next from '../public/next.png'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" /> 
      </Head>
      <section className={styles.headerSection}>
        <main className='container' style={{position:'relative'}}>
          <Navbar About = 'About' Services="Services"/> 
          <div className={styles.headerContent}>
            <h1>I Am  Usama</h1>
            <p data-text = 'Front-end React & Next.js developer'>Front-end React & Next.js developer</p>
          </div>
 
          <div className={styles.iconsDiv}>
          <span><Image src={html} height={70}/></span>
          <span><Image src={css} height={80}/></span>
          <span><Image src={sass} height={80}/></span>
          <span><Image src={js} height={80}/></span>
          <span><Image src={react} height={80}/></span>
          <span><Image src={next} height={80}/></span>
          </div>
         </main>
      </section>
           <SocialLinks/>
           <About id='About'/>

    </>
  );
}
